version: '3.8'

networks:
  elk_next:
    name: elk_next

volumes:
  elk_next:
    driver: local

services:
  elasticsearch:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    environment:
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=basic
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elk_next:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9200
    networks:
      - elk_next

  kibana:
    restart: always
    image: docker.elastic.co/kibana/kibana:7.14.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - elk_next