version: '3.8'

networks:
  elk_7_14:
    name: elk_7_14
    driver: overlay
    attachable: true    

volumes:
  elk_7.14:
    driver: local

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    deploy:
      replicas: 1
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          cpus: '8'
          memory: 3G
    environment:
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=basic
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elk_7.14:/usr/share/elasticsearch/data
    ports:
      - 9201:9200
      - 9301:9300
    networks:
      - elk_7_14

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.1
    deploy:
      replicas: 1
      rollback_config:
        parallelism: 0
      update_config:
        parallelism: 0
        order: stop-first
        failure_action: rollback
      restart_policy:
        condition: any
        delay: 30s
      resources:
        limits:
          cpus: '2'
          memory: 1024M
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5602:5601
    networks:
      - elk_7_14