name: deployment@7.14

on:
  push:
    branches:
      - 7.14

jobs:
  deploy:
    runs-on: github-runner.saeon.int
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 7.14

      - name: (SCP) Copy Docker files to host
        uses: appleboy/scp-action@master
        with:
          host: elasticsearch.saeon.int
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_SSH_PORT }}
          source: "src/7.14/docker-compose.yml"
          target: "deploy"

      - name: (SSH) Deploy Docker stack
        uses: appleboy/ssh-action@master
        with:
          host: elasticsearch.saeon.int
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_SSH_PORT }}
          script: sudo /opt/deploy-docker-stack.sh /home/runner/deploy/src/7.14/docker-compose.yml elk_7_14