name: deployment@7.14

on:
  push:
    branches:
      - 7.14

jobs:
  deploy:
    runs-on: github-runner.saeon.int
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 7.14

      - name: Copy source
        run: |
          ssh runner@192.168.110.105 'mkdir -p deploy/7.14'
          scp src/7.14/* runner@192.168.110.105:deploy/7.14/

      - name: Deploy stack
        run: |
          ssh runner@192.168.110.105 'sudo /opt/deploy-docker-stack.sh /home/runner/deploy/7.14/docker-compose.yml elk_7_14'