name: deployment@next

on:
  push:
    branches:
      - next

jobs:
  deploy:
    runs-on: github-runner.saeon.int
    steps:
      - uses: actions/checkout@v2
        with:
          ref: next

      - name: Execute SSH commands on remote server
        uses: appleboy/ssh-action@master
        with:
            host: elasticsearch.saeon.int
            username: ${{ secrets.SAEON_RUNNER_HOST_USERNAME }}
            script: whoami

      # - name: Copy source
      #   run: |
      #     ssh runner@elasticsearch.saeon.int 'mkdir -p deploy/next'
      #     scp src/next/* runner@elasticsearch.saeon.int:deploy/next/

      # - name: Deploy stack
      #   run: |
      #     ssh runner@elasticsearch.saeon.int 'sudo /opt/deploy-docker-stack.sh /home/runner/deploy/next/docker-compose.yml elk_next'