name: deployment@next

on:
  push:
    branches:
      - next

jobs:
  deploy:
    runs-on: github-runner.saeon.int
    steps:
      - uses: actions/checkout@v2
        with:
          ref: next

      - name: test
        run: |
          scp README.md runner@192.168.110.105:
          echo hi2