name: integration@nccis-qgis-index

on:
  schedule:
    - cron:  '*/10 * * * *'
  push:
    branches:
      - 7.14


env:
  REGISTRY: ghcr.io
  API_IMAGE_NAME: saeon/elk-integration
  BRANCH_REF: 7.14

jobs:
  build-script-image:
    runs-on: ubuntu-latest
    outpus:
      image: ${{ steps.meta.outputs.tags }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_REF }}

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: integrations/nccis-qgis-index
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  run-integration:
    needs: [build-script-image]
    runs-on: github-runner.saeon.int
    steps:
      - name: Execute integration
        run: |
          echo "hi"